<?php

use Cars\Models\Provincia;
use Illuminate\Database\Seeder;

class ProvinciaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Provincia::create(['codigo' => '010100','nombre' => 'CHACHAPOYAS', 'descripcion' => 'AMAZONAS/CHACHAPOYAS','idregion' => 1]);
		Provincia::create(['codigo' => '010200','nombre' => 'BAGUA', 'descripcion' => 'AMAZONAS/BAGUA','idregion' => 1]);
		Provincia::create(['codigo' => '010300','nombre' => 'BONGARA', 'descripcion' => 'AMAZONAS/BONGARA','idregion' => 1]);
		Provincia::create(['codigo' => '010400','nombre' => 'LUYA', 'descripcion' => 'AMAZONAS/LUYA','idregion' => 1]);
		Provincia::create(['codigo' => '010500','nombre' => 'RODRIGUEZ DE MENDOZA', 'descripcion' => 'AMAZONAS/RODRIGUEZ DE MENDOZA','idregion' => 1]);
		Provincia::create(['codigo' => '010600','nombre' => 'CONDORCANQUI', 'descripcion' => 'AMAZONAS/CONDORCANQUI','idregion' => 1]);
		Provincia::create(['codigo' => '010700','nombre' => 'UTCUBAMBA', 'descripcion' => 'AMAZONAS/UTCUBAMBA','idregion' => 1]);
		Provincia::create(['codigo' => '020100','nombre' => 'HUARAZ', 'descripcion' => 'ANCASH/HUARAZ','idregion' => 2]);
		Provincia::create(['codigo' => '020200','nombre' => 'AIJA', 'descripcion' => 'ANCASH/AIJA','idregion' => 2]);
		Provincia::create(['codigo' => '020300','nombre' => 'BOLOGNESI', 'descripcion' => 'ANCASH/BOLOGNESI','idregion' => 2]);
		Provincia::create(['codigo' => '020400','nombre' => 'CARHUAZ', 'descripcion' => 'ANCASH/CARHUAZ','idregion' => 2]);
		Provincia::create(['codigo' => '020500','nombre' => 'CASMA', 'descripcion' => 'ANCASH/CASMA','idregion' => 2]);
		Provincia::create(['codigo' => '020600','nombre' => 'CORONGO', 'descripcion' => 'ANCASH/CORONGO','idregion' => 2]);
		Provincia::create(['codigo' => '020700','nombre' => 'HUAYLAS', 'descripcion' => 'ANCASH/HUAYLAS','idregion' => 2]);
		Provincia::create(['codigo' => '020800','nombre' => 'HUARI', 'descripcion' => 'ANCASH/HUARI','idregion' => 2]);
		Provincia::create(['codigo' => '020900','nombre' => 'MARISCAL LUZURIAGA', 'descripcion' => 'ANCASH/MARISCAL LUZURIAGA','idregion' => 2]);
		Provincia::create(['codigo' => '021000','nombre' => 'PALLASCA', 'descripcion' => 'ANCASH/PALLASCA','idregion' => 2]);
		Provincia::create(['codigo' => '021100','nombre' => 'POMABAMBA', 'descripcion' => 'ANCASH/POMABAMBA','idregion' => 2]);
		Provincia::create(['codigo' => '021200','nombre' => 'RECUAY', 'descripcion' => 'ANCASH/RECUAY','idregion' => 2]);
		Provincia::create(['codigo' => '021300','nombre' => 'SANTA', 'descripcion' => 'ANCASH/SANTA','idregion' => 2]);
		Provincia::create(['codigo' => '021400','nombre' => 'SIHUAS', 'descripcion' => 'ANCASH/SIHUAS','idregion' => 2]);
		Provincia::create(['codigo' => '021500','nombre' => 'YUNGAY', 'descripcion' => 'ANCASH/YUNGAY','idregion' => 2]);
		Provincia::create(['codigo' => '021600','nombre' => 'ANTONIO RAIMONDI', 'descripcion' => 'ANCASH/ANTONIO RAIMONDI','idregion' => 2]);
		Provincia::create(['codigo' => '021700','nombre' => 'CARLOS FERMIN FITZCARRALD', 'descripcion' => 'ANCASH/CARLOS FERMIN FITZCARRALD','idregion' => 2]);
		Provincia::create(['codigo' => '021800','nombre' => 'ASUNCION', 'descripcion' => 'ANCASH/ASUNCION','idregion' => 2]);
		Provincia::create(['codigo' => '021900','nombre' => 'HUARMEY', 'descripcion' => 'ANCASH/HUARMEY','idregion' => 2]);
		Provincia::create(['codigo' => '022000','nombre' => 'OCROS', 'descripcion' => 'ANCASH/OCROS','idregion' => 2]);
		Provincia::create(['codigo' => '030100','nombre' => 'ABANCAY', 'descripcion' => 'APURIMAC/ABANCAY','idregion' => 3]);
		Provincia::create(['codigo' => '030200','nombre' => 'AYMARAES', 'descripcion' => 'APURIMAC/AYMARAES','idregion' => 3]);
		Provincia::create(['codigo' => '030300','nombre' => 'ANDAHUAYLAS', 'descripcion' => 'APURIMAC/ANDAHUAYLAS','idregion' => 3]);
		Provincia::create(['codigo' => '030400','nombre' => 'ANTABAMBA', 'descripcion' => 'APURIMAC/ANTABAMBA','idregion' => 3]);
		Provincia::create(['codigo' => '030500','nombre' => 'COTABAMBAS', 'descripcion' => 'APURIMAC/COTABAMBAS','idregion' => 3]);
		Provincia::create(['codigo' => '030600','nombre' => 'GRAU', 'descripcion' => 'APURIMAC/GRAU','idregion' => 3]);
		Provincia::create(['codigo' => '030700','nombre' => 'CHINCHEROS', 'descripcion' => 'APURIMAC/CHINCHEROS','idregion' => 3]);
		Provincia::create(['codigo' => '040100','nombre' => 'AREQUIPA', 'descripcion' => 'AREQUIPA/AREQUIPA','idregion' => 4]);
		Provincia::create(['codigo' => '040200','nombre' => 'CAYLLOMA', 'descripcion' => 'AREQUIPA/CAYLLOMA','idregion' => 4]);
		Provincia::create(['codigo' => '040300','nombre' => 'CAMANA', 'descripcion' => 'AREQUIPA/CAMANA','idregion' => 4]);
		Provincia::create(['codigo' => '040400','nombre' => 'CARAVELI', 'descripcion' => 'AREQUIPA/CARAVELI','idregion' => 4]);
		Provincia::create(['codigo' => '040500','nombre' => 'CASTILLA', 'descripcion' => 'AREQUIPA/CASTILLA','idregion' => 4]);
		Provincia::create(['codigo' => '040600','nombre' => 'CONDESUYOS', 'descripcion' => 'AREQUIPA/CONDESUYOS','idregion' => 4]);
		Provincia::create(['codigo' => '040700','nombre' => 'ISLAY', 'descripcion' => 'AREQUIPA/ISLAY','idregion' => 4]);
		Provincia::create(['codigo' => '040800','nombre' => 'LA UNION', 'descripcion' => 'AREQUIPA/LA UNION','idregion' => 4]);
		Provincia::create(['codigo' => '050100','nombre' => 'HUAMANGA', 'descripcion' => 'AYACUCHO/HUAMANGA','idregion' => 5]);
		Provincia::create(['codigo' => '050200','nombre' => 'CANGALLO', 'descripcion' => 'AYACUCHO/CANGALLO','idregion' => 5]);
		Provincia::create(['codigo' => '050300','nombre' => 'HUANTA', 'descripcion' => 'AYACUCHO/HUANTA','idregion' => 5]);
		Provincia::create(['codigo' => '050400','nombre' => 'LA MAR', 'descripcion' => 'AYACUCHO/LA MAR','idregion' => 5]);
		Provincia::create(['codigo' => '050500','nombre' => 'LUCANAS', 'descripcion' => 'AYACUCHO/LUCANAS','idregion' => 5]);
		Provincia::create(['codigo' => '050600','nombre' => 'PARINACOCHAS', 'descripcion' => 'AYACUCHO/PARINACOCHAS','idregion' => 5]);
		Provincia::create(['codigo' => '050700','nombre' => 'VICTOR FAJARDO', 'descripcion' => 'AYACUCHO/VICTOR FAJARDO','idregion' => 5]);
		Provincia::create(['codigo' => '050800','nombre' => 'HUANCA SANCOS', 'descripcion' => 'AYACUCHO/HUANCA SANCOS','idregion' => 5]);
		Provincia::create(['codigo' => '050900','nombre' => 'VILCAS HUAMAN', 'descripcion' => 'AYACUCHO/VILCAS HUAMAN','idregion' => 5]);
		Provincia::create(['codigo' => '051000','nombre' => 'PAUCAR DEL SARA SARA', 'descripcion' => 'AYACUCHO/PAUCAR DEL SARA SARA','idregion' => 5]);
		Provincia::create(['codigo' => '051100','nombre' => 'SUCRE', 'descripcion' => 'AYACUCHO/SUCRE','idregion' => 5]);
		Provincia::create(['codigo' => '060100','nombre' => 'CAJAMARCA', 'descripcion' => 'CAJAMARCA/CAJAMARCA','idregion' => 6]);
		Provincia::create(['codigo' => '060200','nombre' => 'CAJABAMBA', 'descripcion' => 'CAJAMARCA/CAJABAMBA','idregion' => 6]);
		Provincia::create(['codigo' => '060300','nombre' => 'CELENDIN', 'descripcion' => 'CAJAMARCA/CELENDIN','idregion' => 6]);
		Provincia::create(['codigo' => '060400','nombre' => 'CONTUMAZA', 'descripcion' => 'CAJAMARCA/CONTUMAZA','idregion' => 6]);
		Provincia::create(['codigo' => '060500','nombre' => 'CUTERVO', 'descripcion' => 'CAJAMARCA/CUTERVO','idregion' => 6]);
		Provincia::create(['codigo' => '060600','nombre' => 'CHOTA', 'descripcion' => 'CAJAMARCA/CHOTA','idregion' => 6]);
		Provincia::create(['codigo' => '060700','nombre' => 'HUALGAYOC', 'descripcion' => 'CAJAMARCA/HUALGAYOC','idregion' => 6]);
		Provincia::create(['codigo' => '060800','nombre' => 'JAEN', 'descripcion' => 'CAJAMARCA/JAEN','idregion' => 6]);
		Provincia::create(['codigo' => '060900','nombre' => 'SANTA CRUZ', 'descripcion' => 'CAJAMARCA/SANTA CRUZ','idregion' => 6]);
		Provincia::create(['codigo' => '061000','nombre' => 'SAN MIGUEL', 'descripcion' => 'CAJAMARCA/SAN MIGUEL','idregion' => 6]);
		Provincia::create(['codigo' => '061100','nombre' => 'SAN IGNACIO', 'descripcion' => 'CAJAMARCA/SAN IGNACIO','idregion' => 6]);
		Provincia::create(['codigo' => '061200','nombre' => 'SAN MARCOS', 'descripcion' => 'CAJAMARCA/SAN MARCOS','idregion' => 6]);
		Provincia::create(['codigo' => '061300','nombre' => 'SAN PABLO', 'descripcion' => 'CAJAMARCA/SAN PABLO','idregion' => 6]);
		Provincia::create(['codigo' => '070100','nombre' => 'CUSCO', 'descripcion' => 'CUSCO/CUSCO','idregion' => 7]);
		Provincia::create(['codigo' => '070200','nombre' => 'ACOMAYO', 'descripcion' => 'CUSCO/ACOMAYO','idregion' => 7]);
		Provincia::create(['codigo' => '070300','nombre' => 'ANTA', 'descripcion' => 'CUSCO/ANTA','idregion' => 7]);
		Provincia::create(['codigo' => '070400','nombre' => 'CALCA', 'descripcion' => 'CUSCO/CALCA','idregion' => 7]);
		Provincia::create(['codigo' => '070500','nombre' => 'CANAS', 'descripcion' => 'CUSCO/CANAS','idregion' => 7]);
		Provincia::create(['codigo' => '070600','nombre' => 'CANCHIS', 'descripcion' => 'CUSCO/CANCHIS','idregion' => 7]);
		Provincia::create(['codigo' => '070700','nombre' => 'CHUMBIVILCAS', 'descripcion' => 'CUSCO/CHUMBIVILCAS','idregion' => 7]);
		Provincia::create(['codigo' => '070800','nombre' => 'ESPINAR', 'descripcion' => 'CUSCO/ESPINAR','idregion' => 7]);
		Provincia::create(['codigo' => '070900','nombre' => 'LA CONVENCION', 'descripcion' => 'CUSCO/LA CONVENCION','idregion' => 7]);
		Provincia::create(['codigo' => '071000','nombre' => 'PARURO', 'descripcion' => 'CUSCO/PARURO','idregion' => 7]);
		Provincia::create(['codigo' => '071100','nombre' => 'PAUCARTAMBO', 'descripcion' => 'CUSCO/PAUCARTAMBO','idregion' => 7]);
		Provincia::create(['codigo' => '071200','nombre' => 'QUISPICANCHI', 'descripcion' => 'CUSCO/QUISPICANCHI','idregion' => 7]);
		Provincia::create(['codigo' => '071300','nombre' => 'URUBAMBA', 'descripcion' => 'CUSCO/URUBAMBA','idregion' => 7]);
		Provincia::create(['codigo' => '080100','nombre' => 'HUANCAVELICA', 'descripcion' => 'HUANCAVELICA/HUANCAVELICA','idregion' => 8]);
		Provincia::create(['codigo' => '080200','nombre' => 'ACOBAMBA', 'descripcion' => 'HUANCAVELICA/ACOBAMBA','idregion' => 8]);
		Provincia::create(['codigo' => '080300','nombre' => 'ANGARAES', 'descripcion' => 'HUANCAVELICA/ANGARAES','idregion' => 8]);
		Provincia::create(['codigo' => '080400','nombre' => 'CASTROVIRREYNA', 'descripcion' => 'HUANCAVELICA/CASTROVIRREYNA','idregion' => 8]);
		Provincia::create(['codigo' => '080500','nombre' => 'TAYACAJA', 'descripcion' => 'HUANCAVELICA/TAYACAJA','idregion' => 8]);
		Provincia::create(['codigo' => '080600','nombre' => 'HUAYTARA', 'descripcion' => 'HUANCAVELICA/HUAYTARA','idregion' => 8]);
		Provincia::create(['codigo' => '080700','nombre' => 'CHURCAMPA', 'descripcion' => 'HUANCAVELICA/CHURCAMPA','idregion' => 8]);
		Provincia::create(['codigo' => '090100','nombre' => 'HUANUCO', 'descripcion' => 'HUANUCO/HUANUCO','idregion' => 9]);
		Provincia::create(['codigo' => '090200','nombre' => 'AMBO', 'descripcion' => 'HUANUCO/AMBO','idregion' => 9]);
		Provincia::create(['codigo' => '090300','nombre' => 'DOS DE MAYO', 'descripcion' => 'HUANUCO/DOS DE MAYO','idregion' => 9]);
		Provincia::create(['codigo' => '090400','nombre' => 'HUAMALIES', 'descripcion' => 'HUANUCO/HUAMALIES','idregion' => 9]);
		Provincia::create(['codigo' => '090500','nombre' => 'MARAÑON', 'descripcion' => 'HUANUCO/MARAÑON','idregion' => 9]);
		Provincia::create(['codigo' => '090600','nombre' => 'LEONCIO PRADO', 'descripcion' => 'HUANUCO/LEONCIO PRADO','idregion' => 9]);
		Provincia::create(['codigo' => '090700','nombre' => 'PACHITEA', 'descripcion' => 'HUANUCO/PACHITEA','idregion' => 9]);
		Provincia::create(['codigo' => '090800','nombre' => 'PUERTO INCA', 'descripcion' => 'HUANUCO/PUERTO INCA','idregion' => 9]);
		Provincia::create(['codigo' => '090900','nombre' => 'HUACAYBAMBA', 'descripcion' => 'HUANUCO/HUACAYBAMBA','idregion' => 9]);
		Provincia::create(['codigo' => '091000','nombre' => 'LAURICOCHA', 'descripcion' => 'HUANUCO/LAURICOCHA','idregion' => 9]);
		Provincia::create(['codigo' => '091100','nombre' => 'YAROWILCA', 'descripcion' => 'HUANUCO/YAROWILCA','idregion' => 9]);
		Provincia::create(['codigo' => '100100','nombre' => 'ICA', 'descripcion' => 'ICA/ICA','idregion' => 10]);
		Provincia::create(['codigo' => '100200','nombre' => 'CHINCHA', 'descripcion' => 'ICA/CHINCHA','idregion' => 10]);
		Provincia::create(['codigo' => '100300','nombre' => 'NAZCA', 'descripcion' => 'ICA/NAZCA','idregion' => 10]);
		Provincia::create(['codigo' => '100400','nombre' => 'PISCO', 'descripcion' => 'ICA/PISCO','idregion' => 10]);
		Provincia::create(['codigo' => '100500','nombre' => 'PALPA', 'descripcion' => 'ICA/PALPA','idregion' => 10]);
		Provincia::create(['codigo' => '110100','nombre' => 'HUANCAYO', 'descripcion' => 'JUNIN/HUANCAYO','idregion' => 11]);
		Provincia::create(['codigo' => '110200','nombre' => 'CONCEPCION', 'descripcion' => 'JUNIN/CONCEPCION','idregion' => 11]);
		Provincia::create(['codigo' => '110300','nombre' => 'JAUJA', 'descripcion' => 'JUNIN/JAUJA','idregion' => 11]);
		Provincia::create(['codigo' => '110400','nombre' => 'JUNIN', 'descripcion' => 'JUNIN/JUNIN','idregion' => 11]);
		Provincia::create(['codigo' => '110500','nombre' => 'TARMA', 'descripcion' => 'JUNIN/TARMA','idregion' => 11]);
		Provincia::create(['codigo' => '110600','nombre' => 'YAULI', 'descripcion' => 'JUNIN/YAULI','idregion' => 11]);
		Provincia::create(['codigo' => '110700','nombre' => 'SATIPO', 'descripcion' => 'JUNIN/SATIPO','idregion' => 11]);
		Provincia::create(['codigo' => '110800','nombre' => 'CHANCHAMAYO', 'descripcion' => 'JUNIN/CHANCHAMAYO','idregion' => 11]);
		Provincia::create(['codigo' => '110900','nombre' => 'CHUPACA', 'descripcion' => 'JUNIN/CHUPACA','idregion' => 11]);
		Provincia::create(['codigo' => '120100','nombre' => 'TRUJILLO', 'descripcion' => 'LA LIBERTAD/TRUJILLO','idregion' => 12]);
		Provincia::create(['codigo' => '120200','nombre' => 'BOLIVAR', 'descripcion' => 'LA LIBERTAD/BOLIVAR','idregion' => 12]);
		Provincia::create(['codigo' => '120300','nombre' => 'SANCHEZ CARRION', 'descripcion' => 'LA LIBERTAD/SANCHEZ CARRION','idregion' => 12]);
		Provincia::create(['codigo' => '120400','nombre' => 'OTUZCO', 'descripcion' => 'LA LIBERTAD/OTUZCO','idregion' => 12]);
		Provincia::create(['codigo' => '120500','nombre' => 'PACASMAYO', 'descripcion' => 'LA LIBERTAD/PACASMAYO','idregion' => 12]);
		Provincia::create(['codigo' => '120600','nombre' => 'PATAZ', 'descripcion' => 'LA LIBERTAD/PATAZ','idregion' => 12]);
		Provincia::create(['codigo' => '120700','nombre' => 'SANTIAGO DE CHUCO', 'descripcion' => 'LA LIBERTAD/SANTIAGO DE CHUCO','idregion' => 12]);
		Provincia::create(['codigo' => '120800','nombre' => 'ASCOPE', 'descripcion' => 'LA LIBERTAD/ASCOPE','idregion' => 12]);
		Provincia::create(['codigo' => '120900','nombre' => 'CHEPEN', 'descripcion' => 'LA LIBERTAD/CHEPEN','idregion' => 12]);
		Provincia::create(['codigo' => '121000','nombre' => 'JULCAN', 'descripcion' => 'LA LIBERTAD/JULCAN','idregion' => 12]);
		Provincia::create(['codigo' => '121100','nombre' => 'GRAN CHIMU', 'descripcion' => 'LA LIBERTAD/GRAN CHIMU','idregion' => 12]);
		Provincia::create(['codigo' => '121200','nombre' => 'VIRU', 'descripcion' => 'LA LIBERTAD/VIRU','idregion' => 12]);
		Provincia::create(['codigo' => '130100','nombre' => 'CHICLAYO', 'descripcion' => 'LAMBAYEQUE/CHICLAYO','idregion' => 13]);
		Provincia::create(['codigo' => '130200','nombre' => 'FERREÑAFE', 'descripcion' => 'LAMBAYEQUE/FERREÑAFE','idregion' => 13]);
		Provincia::create(['codigo' => '130300','nombre' => 'LAMBAYEQUE', 'descripcion' => 'LAMBAYEQUE/LAMBAYEQUE','idregion' => 13]);
		Provincia::create(['codigo' => '140100','nombre' => 'LIMA', 'descripcion' => 'LIMA/LIMA','idregion' => 14]);
		Provincia::create(['codigo' => '140200','nombre' => 'CAJATAMBO', 'descripcion' => 'LIMA/CAJATAMBO','idregion' => 14]);
		Provincia::create(['codigo' => '140300','nombre' => 'CANTA', 'descripcion' => 'LIMA/CANTA','idregion' => 14]);
		Provincia::create(['codigo' => '140400','nombre' => 'CAÑETE', 'descripcion' => 'LIMA/CAÑETE','idregion' => 14]);
		Provincia::create(['codigo' => '140500','nombre' => 'HUAURA', 'descripcion' => 'LIMA/HUAURA','idregion' => 14]);
		Provincia::create(['codigo' => '140600','nombre' => 'HUAROCHIRI', 'descripcion' => 'LIMA/HUAROCHIRI','idregion' => 14]);
		Provincia::create(['codigo' => '140700','nombre' => 'YAUYOS', 'descripcion' => 'LIMA/YAUYOS','idregion' => 14]);
		Provincia::create(['codigo' => '140800','nombre' => 'HUARAL', 'descripcion' => 'LIMA/HUARAL','idregion' => 14]);
		Provincia::create(['codigo' => '140900','nombre' => 'BARRANCA', 'descripcion' => 'LIMA/BARRANCA','idregion' => 14]);
		Provincia::create(['codigo' => '141000','nombre' => 'OYON', 'descripcion' => 'LIMA/OYON','idregion' => 14]);
		Provincia::create(['codigo' => '150100','nombre' => 'MAYNAS', 'descripcion' => 'LORETO/MAYNAS','idregion' => 15]);
		Provincia::create(['codigo' => '150200','nombre' => 'ALTO AMAZONAS', 'descripcion' => 'LORETO/ALTO AMAZONAS','idregion' => 15]);
		Provincia::create(['codigo' => '150300','nombre' => 'LORETO', 'descripcion' => 'LORETO/LORETO','idregion' => 15]);
		Provincia::create(['codigo' => '150400','nombre' => 'REQUENA', 'descripcion' => 'LORETO/REQUENA','idregion' => 15]);
		Provincia::create(['codigo' => '150500','nombre' => 'UCAYALI', 'descripcion' => 'LORETO/UCAYALI','idregion' => 15]);
		Provincia::create(['codigo' => '150600','nombre' => 'MARISCAL RAMON CASTILLA', 'descripcion' => 'LORETO/MARISCAL RAMON CASTILLA','idregion' => 15]);
		Provincia::create(['codigo' => '150700','nombre' => 'DATEM DEL MARAÑON', 'descripcion' => 'LORETO/DATEM DEL MARAÑON','idregion' => 15]);
		Provincia::create(['codigo' => '160100','nombre' => 'TAMBOPATA', 'descripcion' => 'MADRE DE DIOS/TAMBOPATA','idregion' => 16]);
		Provincia::create(['codigo' => '160200','nombre' => 'MANU', 'descripcion' => 'MADRE DE DIOS/MANU','idregion' => 16]);
		Provincia::create(['codigo' => '160300','nombre' => 'TAHUAMANU', 'descripcion' => 'MADRE DE DIOS/TAHUAMANU','idregion' => 16]);
		Provincia::create(['codigo' => '170100','nombre' => 'MARISCAL NIETO', 'descripcion' => 'MOQUEGUA/MARISCAL NIETO','idregion' => 17]);
		Provincia::create(['codigo' => '170200','nombre' => 'GENERAL SANCHEZ CERRO', 'descripcion' => 'MOQUEGUA/GENERAL SANCHEZ CERRO','idregion' => 17]);
		Provincia::create(['codigo' => '170300','nombre' => 'ILO', 'descripcion' => 'MOQUEGUA/ILO','idregion' => 17]);
		Provincia::create(['codigo' => '180100','nombre' => 'PASCO', 'descripcion' => 'PASCO/PASCO','idregion' => 18]);
		Provincia::create(['codigo' => '180200','nombre' => 'DANIEL ALCIDES CARRION', 'descripcion' => 'PASCO/DANIEL ALCIDES CARRION','idregion' => 18]);
		Provincia::create(['codigo' => '180300','nombre' => 'OXAPAMPA', 'descripcion' => 'PASCO/OXAPAMPA','idregion' => 18]);
		Provincia::create(['codigo' => '190100','nombre' => 'PIURA', 'descripcion' => 'PIURA/PIURA','idregion' => 19]);
		Provincia::create(['codigo' => '190200','nombre' => 'AYABACA', 'descripcion' => 'PIURA/AYABACA','idregion' => 19]);
		Provincia::create(['codigo' => '190300','nombre' => 'HUANCABAMBA', 'descripcion' => 'PIURA/HUANCABAMBA','idregion' => 19]);
		Provincia::create(['codigo' => '190400','nombre' => 'MORROPON', 'descripcion' => 'PIURA/MORROPON','idregion' => 19]);
		Provincia::create(['codigo' => '190500','nombre' => 'PAITA', 'descripcion' => 'PIURA/PAITA','idregion' => 19]);
		Provincia::create(['codigo' => '190600','nombre' => 'SULLANA', 'descripcion' => 'PIURA/SULLANA','idregion' => 19]);
		Provincia::create(['codigo' => '190700','nombre' => 'TALARA', 'descripcion' => 'PIURA/TALARA','idregion' => 19]);
		Provincia::create(['codigo' => '190800','nombre' => 'SECHURA', 'descripcion' => 'PIURA/SECHURA','idregion' => 19]);
		Provincia::create(['codigo' => '200100','nombre' => 'PUNO', 'descripcion' => 'PUNO/PUNO','idregion' => 20]);
		Provincia::create(['codigo' => '200200','nombre' => 'AZANGARO', 'descripcion' => 'PUNO/AZANGARO','idregion' => 20]);
		Provincia::create(['codigo' => '200300','nombre' => 'CARABAYA', 'descripcion' => 'PUNO/CARABAYA','idregion' => 20]);
		Provincia::create(['codigo' => '200400','nombre' => 'CHUCUITO', 'descripcion' => 'PUNO/CHUCUITO','idregion' => 20]);
		Provincia::create(['codigo' => '200500','nombre' => 'HUANCANE', 'descripcion' => 'PUNO/HUANCANE','idregion' => 20]);
		Provincia::create(['codigo' => '200600','nombre' => 'LAMPA', 'descripcion' => 'PUNO/LAMPA','idregion' => 20]);
		Provincia::create(['codigo' => '200700','nombre' => 'MELGAR', 'descripcion' => 'PUNO/MELGAR','idregion' => 20]);
		Provincia::create(['codigo' => '200800','nombre' => 'SANDIA', 'descripcion' => 'PUNO/SANDIA','idregion' => 20]);
		Provincia::create(['codigo' => '200900','nombre' => 'SAN ROMAN', 'descripcion' => 'PUNO/SAN ROMAN','idregion' => 20]);
		Provincia::create(['codigo' => '201000','nombre' => 'YUNGUYO', 'descripcion' => 'PUNO/YUNGUYO','idregion' => 20]);
		Provincia::create(['codigo' => '201100','nombre' => 'SAN ANTONIO DE PUTINA', 'descripcion' => 'PUNO/SAN ANTONIO DE PUTINA','idregion' => 20]);
		Provincia::create(['codigo' => '201200','nombre' => 'EL COLLAO', 'descripcion' => 'PUNO/EL COLLAO','idregion' => 20]);
		Provincia::create(['codigo' => '201300','nombre' => 'MOHO', 'descripcion' => 'PUNO/MOHO','idregion' => 20]);
		Provincia::create(['codigo' => '210100','nombre' => 'MOYOBAMBA', 'descripcion' => 'SAN MARTIN/MOYOBAMBA','idregion' => 21]);
		Provincia::create(['codigo' => '210200','nombre' => 'HUALLAGA', 'descripcion' => 'SAN MARTIN/HUALLAGA','idregion' => 21]);
		Provincia::create(['codigo' => '210300','nombre' => 'LAMAS', 'descripcion' => 'SAN MARTIN/LAMAS','idregion' => 21]);
		Provincia::create(['codigo' => '210400','nombre' => 'MARISCAL CACERES', 'descripcion' => 'SAN MARTIN/MARISCAL CACERES','idregion' => 21]);
		Provincia::create(['codigo' => '210500','nombre' => 'RIOJA', 'descripcion' => 'SAN MARTIN/RIOJA','idregion' => 21]);
		Provincia::create(['codigo' => '210600','nombre' => 'SAN MARTIN', 'descripcion' => 'SAN MARTIN/SAN MARTIN','idregion' => 21]);
		Provincia::create(['codigo' => '210700','nombre' => 'BELLAVISTA', 'descripcion' => 'SAN MARTIN/BELLAVISTA','idregion' => 21]);
		Provincia::create(['codigo' => '210800','nombre' => 'TOCACHE', 'descripcion' => 'SAN MARTIN/TOCACHE','idregion' => 21]);
		Provincia::create(['codigo' => '210900','nombre' => 'PICOTA', 'descripcion' => 'SAN MARTIN/PICOTA','idregion' => 21]);
		Provincia::create(['codigo' => '211000','nombre' => 'EL DORADO', 'descripcion' => 'SAN MARTIN/EL DORADO','idregion' => 21]);
		Provincia::create(['codigo' => '220100','nombre' => 'TACNA', 'descripcion' => 'TACNA/TACNA','idregion' => 22]);
		Provincia::create(['codigo' => '220200','nombre' => 'TARATA', 'descripcion' => 'TACNA/TARATA','idregion' => 22]);
		Provincia::create(['codigo' => '220300','nombre' => 'JORGE BASADRE', 'descripcion' => 'TACNA/JORGE BASADRE','idregion' => 22]);
		Provincia::create(['codigo' => '220400','nombre' => 'CANDARAVE', 'descripcion' => 'TACNA/CANDARAVE','idregion' => 22]);
		Provincia::create(['codigo' => '230100','nombre' => 'TUMBES', 'descripcion' => 'TUMBES/TUMBES','idregion' => 23]);
		Provincia::create(['codigo' => '230200','nombre' => 'CONTRALMIRANTE VILLAR', 'descripcion' => 'TUMBES/CONTRALMIRANTE VILLAR','idregion' => 23]);
		Provincia::create(['codigo' => '230300','nombre' => 'ZARUMILLA', 'descripcion' => 'TUMBES/ZARUMILLA','idregion' => 23]);
		Provincia::create(['codigo' => '240100','nombre' => 'CALLAO', 'descripcion' => 'CALLAO/CALLAO','idregion' => 24]);
		Provincia::create(['codigo' => '250100','nombre' => 'CORONEL PORTILLO', 'descripcion' => 'UCAYALI/CORONEL PORTILLO','idregion' => 25]);
		Provincia::create(['codigo' => '250200','nombre' => 'PADRE ABAD', 'descripcion' => 'UCAYALI/PADRE ABAD','idregion' => 25]);
		Provincia::create(['codigo' => '250300','nombre' => 'ATALAYA', 'descripcion' => 'UCAYALI/ATALAYA','idregion' => 25]);
		Provincia::create(['codigo' => '250400','nombre' => 'PURUS', 'descripcion' => 'UCAYALI/PURUS','idregion' => 25]);

    }
}
